### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [transferwise/create-svg-icon-sprite#1]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by oliverviljamaa** [comment]
Thanks (even though your suggestion seems to be copy-pasted or automatic, sneaky...)!

I don't think performance is a major concern here as we only need to build one simple HTML once (usually in the CI process) and after that, it's served statically.

We chose EJS as it has a big community behind it and the syntax is very straightforward.
